# Generated by Django 4.2.6 on 2023-10-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
