# Generated by Django 4.2.6 on 2023-10-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_author_events_photo_events_product_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RemoveField(
            model_name='events',
            name='author',
        ),
        migrations.RemoveField(
            model_name='events',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
        migrations.RemoveField(
            model_name='events',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='weight',
        ),
    ]
