# Generated by Django 4.2.6 on 2023-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_options_events_author_events_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
        migrations.RemoveField(
            model_name='events',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='events',
            name='weight',
        ),
        migrations.AddField(
            model_name='events',
            name='create_date',
            field=models.FloatField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='Дата события'),
        ),
    ]
