# Generated by Django 4.2.6 on 2023-10-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
    ]
