# Generated by Django 4.2.6 on 2023-10-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_inventary_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventary_event',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Событие'),
        ),
    ]
