# Generated by Django 4.2.6 on 2023-10-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_inventary_event_id_food_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventary_event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
