# Generated by Django 4.2.6 on 2023-10-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('events', '0012_alter_inventary_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Событие')),
                ('product_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Еда')),
            ],
            options={
                'verbose_name': 'Инвентарь для события',
                'verbose_name_plural': 'Инвентарь для событий',
            },
        ),
        migrations.DeleteModel(
            name='Food_event',
        ),
    ]
