# Generated by Django 4.2.6 on 2023-10-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_retailer'),
        ('events', '0014_alter_product_event_options_alter_product_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_event',
            name='product_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Еда'),
        ),
    ]
