# Generated by Django 4.2.6 on 2023-10-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_event',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product_event',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Сумма'),
        ),
    ]
