# Generated by Django 4.2.6 on 2023-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_product_event_quantity_product_event_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_event',
            options={'verbose_name': 'Продукты для события', 'verbose_name_plural': 'Продукты для событий'},
        ),
        migrations.AlterField(
            model_name='product_event',
            name='total',
            field=models.FloatField(null=True, verbose_name='Сумма'),
        ),
    ]
