# Generated by Django 4.2.6 on 2023-10-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_product_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_event',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
