# Generated by Django 4.2.6 on 2023-10-12 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200, null=True, verbose_name='Раздел')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('quantity', models.IntegerField(null=True, verbose_name='Количество')),
                ('photo', models.ImageField(null=True, upload_to='images', verbose_name='Фото')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
