# Generated by Django 4.2.6 on 2023-10-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='total',
            field=models.FloatField(null=True, verbose_name='Сумма'),
        ),
    ]
