# Generated by Django 4.2.6 on 2023-10-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
