# Generated by Django 4.2.6 on 2023-10-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
