# Generated by Django 4.2.6 on 2023-10-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_retailer_delete_supplier'),
        ('product', '0004_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer', verbose_name='Продавец'),
        ),
    ]
