# Generated by Django 4.2.6 on 2023-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
