# Generated by Django 4.2.6 on 2023-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='state_number',
            field=models.CharField(max_length=9, null=True, verbose_name='Номер'),
        ),
    ]
