# Generated by Django 4.2.6 on 2023-10-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_state_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Марка/модель'),
        ),
    ]
